webtalk_init -webtalk_dir D:/computerdesign/SCPU_ctrl/SCPU_ctrl.sim/sim_1/behav/xsim/xsim.dir/SCPU_ctrl_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 12 15:30:29 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d2c59d8c-fbcc-45f6-a5cc-86f83bc6d735" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f56db3febf5e44e39b4b3b0ac569845f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900HS with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4118634655 -regid "" -xml D:/computerdesign/SCPU_ctrl/SCPU_ctrl.sim/sim_1/behav/xsim/xsim.dir/SCPU_ctrl_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/computerdesign/SCPU_ctrl/SCPU_ctrl.sim/sim_1/behav/xsim/xsim.dir/SCPU_ctrl_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/computerdesign/SCPU_ctrl/SCPU_ctrl.sim/sim_1/behav/xsim/xsim.dir/SCPU_ctrl_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
