# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mylinux/mycpu/sourecode/OX_SCPU/OX_SCPU.srcs/sources_1/ip/RAM_B/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mylinux/mycpu/sourecode/OX_SCPU/OX_SCPU.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/mylinux/mycpu/sourecode/OX_SCPU/OX_SCPU.srcs/sources_1/ip/RAM_B/RAM_B.xci
# IP: The module: 'RAM_B' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mylinux/mycpu/sourecode/OX_SCPU/OX_SCPU.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_B'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
