# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CSSEE.xdc

# IP: ip/ROM_D_0_1/ROM_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_D_0 || ORIG_REF_NAME==ROM_D_0} -quiet] -quiet

# IP: ip/SCPU_0_11/SCPU_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SCPU_0 || ORIG_REF_NAME==SCPU_0} -quiet] -quiet

# IP: d:/mylinux/mycpu/sourecode/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/SCPU_0_11/src/DataPath_0/DataPath_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DataPath_0 || ORIG_REF_NAME==DataPath_0} -quiet] -quiet

# IP: d:/mylinux/mycpu/sourecode/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/SCPU_0_11/src/DataPath_0/src/MUX2T1_32_0/MUX2T1_32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet
