# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mylinux/mycpu/sourecode/OExp04_IP2CPU/OExp04_IP2CPU.srcs/sources_1/ip/DataPath_0_12/DataPath_0.xci
# IP: The module: 'DataPath_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/mylinux/mycpu/sourecode/OExp04_IP2CPU/OExp04_IP2CPU.gen/sources_1/ip/DataPath_0_12/src/MUX2T1_32_0/MUX2T1_32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# IP: d:/mylinux/mycpu/sourecode/OExp04_IP2CPU/OExp04_IP2CPU.srcs/sources_1/ip/DataPath_0_12/DataPath_0.xci
# IP: The module: 'DataPath_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/mylinux/mycpu/sourecode/OExp04_IP2CPU/OExp04_IP2CPU.gen/sources_1/ip/DataPath_0_12/src/MUX2T1_32_0/MUX2T1_32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet
