# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/computerdesign/DataPath/tmp_edit_project.srcs/sources_1/ip/ALU_0/ALU_0.xci
# IP: The module: 'ALU_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/or_bit_32_0/or_bit_32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==or_bit_32_0 || ORIG_REF_NAME==or_bit_32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/MUX8T1_32_0/MUX8T1_32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX8T1_32_0 || ORIG_REF_NAME==MUX8T1_32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/xor32_0/xor32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xor32_0 || ORIG_REF_NAME==xor32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/srl32_0/srl32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==srl32_0 || ORIG_REF_NAME==srl32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/nor32_0/nor32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nor32_0 || ORIG_REF_NAME==nor32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/or32_0/or32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==or32_0 || ORIG_REF_NAME==or32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/and32_0/and32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==and32_0 || ORIG_REF_NAME==and32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/adc32_0/adc32_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc32_0 || ORIG_REF_NAME==adc32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.srcs/sources_1/ip/ALU_0/ALU_0.xci
# IP: The module: 'ALU_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/or_bit_32_0/or_bit_32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==or_bit_32_0 || ORIG_REF_NAME==or_bit_32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/MUX8T1_32_0/MUX8T1_32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MUX8T1_32_0 || ORIG_REF_NAME==MUX8T1_32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/xor32_0/xor32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xor32_0 || ORIG_REF_NAME==xor32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/srl32_0/srl32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==srl32_0 || ORIG_REF_NAME==srl32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/nor32_0/nor32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nor32_0 || ORIG_REF_NAME==nor32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/or32_0/or32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==or32_0 || ORIG_REF_NAME==or32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/and32_0/and32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==and32_0 || ORIG_REF_NAME==and32_0} -quiet] -quiet

# IP: d:/computerdesign/DataPath/tmp_edit_project.gen/sources_1/ip/ALU_0/src/adc32_0/adc32_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adc32_0 || ORIG_REF_NAME==adc32_0} -quiet] -quiet
